; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.41"

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.3"

projects[admin][subdir] = "contrib"
projects[admin][version] = "2.0-beta3"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.5"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.6"

projects[simplify][subdir] = "contrib"
projects[simplify][version] = "3.3"

projects[views][subdir] = "contrib"
projects[views][version] = "3.13"

projects[workbench][subdir] = "contrib"
projects[workbench][version] = "1.2"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

; Themes
projects[bootstrap][version] = "3.4"

projects[rubik][version] = "4.3"

projects[tao][version] = "3.1"

projects[zen][version] = "5.6"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[profile][download][type] = ""
projects[profile][download][url] = ""
projects[profile][type] = "theme"

